version: "2"

services:
  database:
    image: "postgres:10-alpine"
    restart: always
    ports:
      - 5456:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "workshop"
      POSTGRES_PASSWORD: "graphql"
    network_mode: bridge